#!/usr/bin/env python3
"""
Claude PR Review Script
Reviews GitHub PRs using Claude API with special handling for Dependabot
"""

import os
import json
import sys
from anthropic import Anthropic
from github import Github, Auth

def get_pr_details():
    """Get PR details from GitHub API"""
    token = os.getenv('GITHUB_TOKEN')
    owner = os.getenv('REPO_OWNER')
    repo = os.getenv('REPO_NAME')
    pr_number = int(os.getenv('PR_NUMBER'))

    g = Github(auth=Auth.Token(token))
    repository = g.get_repo(f"{owner}/{repo}")
    pr = repository.get_pull(pr_number)
    
    return pr

def get_pr_diff(pr):
    """Get the diff from a PR"""
    diff = pr.get_commits().reversed[0].commit.message if pr.get_commits().totalCount > 0 else ""
    
    # Get changed files
    files_info = []
    for file in pr.get_files():
        files_info.append({
            'filename': file.filename,
            'additions': file.additions,
            'deletions': file.deletions,
            'patch': file.patch or "No patch available",
            'status': file.status
        })
    
    return {
        'title': pr.title,
        'body': pr.body or "",
        'author': pr.user.login,
        'is_dependabot': pr.user.login == 'dependabot[bot]',
        'files': files_info,
        'commits': pr.get_commits().totalCount
    }

def build_review_prompt(pr_data):
    """Build the Claude prompt for code review"""
    is_dependabot = pr_data['is_dependabot']
    
    if is_dependabot:
        prompt = f"""Review this Dependabot PR and provide a BRIEF summary:

PR Title: {pr_data['title']}
Files changed: {len(pr_data['files'])}

Files:
"""
        for file in pr_data['files']:
            prompt += f"\n- {file['filename']} ({file['status']}, +{file['additions']}/-{file['deletions']} lines)"
        
        prompt += """

Provide a SHORT summary with:
1. **Type**: Functional update / Security patch / Bug fix / Minor version / Major version
2. **Risk Level**: Low / Medium / High
3. **Key Changes**: Brief bullet points (max 3)
4. **Action Required**: Yes/No - any manual testing needed?

Keep it concise - this is a Dependabot update."""
    else:
        prompt = f"""Perform a detailed code review for this PR:

PR Title: {pr_data['title']}
Description: {pr_data['body']}
Author: {pr_data['author']}
Files changed: {len(pr_data['files'])}

Changed files:
"""
        for file in pr_data['files']:
            prompt += f"\n\n## File: {file['filename']} ({file['status']})\n"
            if file['patch']:
                prompt += f"```diff\n{file['patch'][:2000]}\n```"
        
        prompt += """

Provide a detailed review covering:
1. **DRY Principle**: Are there any code duplications that could be refactored?
2. **Best Practices**: Shell scripts, Docker configs, Python code - any issues?
3. **Security**: Any security concerns or hardening opportunities?
4. **Maintainability**: Is the code clear and maintainable? Any suggestions?
5. **Architecture**: Does this follow the project's patterns?
6. **Suggestions**: Any concrete improvements with code examples?

Be constructive and specific with your feedback."""
    
    return prompt

def review_with_claude(pr_data):
    """Send PR to Claude for review"""
    client = Anthropic()
    prompt = build_review_prompt(pr_data)
    
    message = client.messages.create(
        model="claude-opus-4-5-20251101",
        max_tokens=1500,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    return message.content[0].text

def format_github_comment(review, pr_data):
    """Format review as GitHub comment"""
    is_dependabot = pr_data['is_dependabot']
    
    if is_dependabot:
        header = "🤖 **Dependabot PR Summary** (by Claude)"
    else:
        header = "🔍 **Code Review** (by Claude)"
    
    comment = f"""## {header}

{review}

---
*Review generated by Claude AI. Please use your judgment for final approval.*
"""
    
    return comment

def main():
    try:
        print("📥 Fetching PR details...")
        pr = get_pr_details()
        
        print(f"📊 Analyzing PR #{pr.number}: {pr.title}")
        pr_data = get_pr_diff(pr)
        
        print(f"🤖 Sending to Claude (Dependabot: {pr_data['is_dependabot']})...")
        review = review_with_claude(pr_data)
        
        print("📝 Formatting comment...")
        comment = format_github_comment(review, pr_data)
        
        # Write to file for GitHub Action to pick up
        with open('/tmp/claude_review.md', 'w') as f:
            f.write(comment)
        
        print("✅ Review complete!")
        print(comment)
        
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()
