services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2026.4.4@sha256:c1e5f0147f4cb51ccb05bb30b62a1269cc1bd48a6274792d3b38a77ab274dfd2
    devices:
      - /dev/ttyACM0 # mappes zigbee Dongel to container
    network_mode: "host"
    volumes:
      - './homeassistant/config:/config'
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
    user: root
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  matter-hub:
    image: ghcr.io/riddix/home-assistant-matter-hub:2.0.41@sha256:400b1d6e167656733d8fefb0afc2c11e2a2f0257c19ac58cf498ed65a7432057
    container_name: matter-hub
    restart: unless-stopped
    network_mode: host
    # default Port is 8482
    env_file:
      - .env
    volumes:
      - $PWD/home-assistant-matter-hub:/data
  music-assistant:
    image: ghcr.io/music-assistant/server:2.8.6@sha256:400697b305e45bd1712c019e67d22681219e91deb41afe88939f921b5fae137f
    container_name: musicassistant
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: "host"
    volumes:
      - ./musicassistant/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=error
