services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2026.7.0@sha256:cb76c9922b530f6a5063a15463eb3ad6de287d297c826713abda16795bb98980
    devices:
      - /dev/ttyACM0 # mappes zigbee Dongel to container
    network_mode: "host"
    volumes:
      - "./homeassistant/config:/config"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:212f89e1eaeb2c322d6441b64396e3346026674db8fa9c27beac293405c32b3c
    user: root
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  matter-hub:
    image: ghcr.io/riddix/home-assistant-matter-hub:2.0.48@sha256:9f638549d2c6dfa614507e5c408bb4970a7fa674bef38c4c9ae4a3712a0ba739
    container_name: matter-hub
    restart: unless-stopped
    network_mode: host
    # default Port is 8482
    env_file:
      - .env
    volumes:
      - $PWD/home-assistant-matter-hub:/data
