services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2026.9.2@sha256:a1bc133af84ee6505fe2c266d9805b7c75b780dfdc188edfee3b11e8f3cd8efe
    devices:
      - /dev/ttyACM0 # mappes zigbee Dongel to container
    network_mode: "host"
    volumes:
      - "./homeassistant/config:/config"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:212f89e1eaeb2c322d6441b64396e3346026674db8fa9c27beac293405c32b3c
    user: root
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  matter-hub:
    image: ghcr.io/riddix/home-assistant-matter-hub:2.0.57@sha256:3f63aca9cd94162c0736859b43949e95d164d2d47dbd1239574738e583c77661
    container_name: matter-hub
    restart: unless-stopped
    network_mode: host
    # default Port is 8482
    env_file:
      - .env
    volumes:
      - $PWD/home-assistant-matter-hub:/data
